# Source shared config
source-file ~/.tmux.shared.conf

#-- Configure C-space as prefix/escape {
# set C-space as global prefix
set-option -g prefix C-space

# bind C-Space as send-prefix
bind C-space send-prefix
# }

#-- other bindings
# bind R source-file '~/.tmux.conf' <-- already working out of the box due to tmux-sensible plugin?
bind C-space last-window

# -- configure tmux-suspend
set -g @suspend_key 'F10'

# -- configure tmux-continuum
set -g @continuum-restore 'on'

# -- configure tmux-resurrect, restore nvim sessions
set -g @resurrect-strategy-nvim 'session'

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'erikw/tmux-powerline'
set -g @plugin 'MunifTanjim/tmux-suspend'
set -g @plugin 'tmux-plugins/tmux-continuum'

# tmux-resurrect with settings
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @resurrect-capture-pane-contents 'on'

run '~/.tmux/plugins/tpm/tpm'
