# tmux-powerline config for project sessions (nested tmux via tp)
# Modeline {
#	 vi: foldmarker={,} foldmethod=marker foldlevel=0 tabstop=4 filetype=sh
# }

# General {
	export TMUX_POWERLINE_DEBUG_MODE_ENABLED="false"
	export TMUX_POWERLINE_ERROR_LOGS_ENABLED="true"
	export TMUX_POWERLINE_ERROR_LOGS_SCOPES=""
	export TMUX_POWERLINE_PATCHED_FONT_IN_USE="true"

	export TMUX_POWERLINE_THEME="xx4h-slim-project"
	export TMUX_POWERLINE_DIR_USER_THEMES="${XDG_CONFIG_HOME:-$HOME/.config}/tmux-powerline/themes"
	export TMUX_POWERLINE_DIR_USER_SEGMENTS="${XDG_CONFIG_HOME:-$HOME/.config}/tmux-powerline/segments"

	export TMUX_POWERLINE_STATUS_VISIBILITY="on"
	export TMUX_POWERLINE_STATUS_INTERVAL="15"
	export TMUX_POWERLINE_STATUS_JUSTIFICATION="absolute-centre"

	export TMUX_POWERLINE_STATUS_LEFT_LENGTH="0"
	export TMUX_POWERLINE_STATUS_RIGHT_LENGTH="0"

	export TMUX_POWERLINE_WINDOW_STATUS_SEPARATOR=""
# }

# pwd.sh {
	export TMUX_POWERLINE_SEG_PWD_MAX_LEN="120"
# }

# tmux_session_info.sh {
	export TMUX_POWERLINE_SEG_TMUX_SESSION_INFO_FORMAT="#S:#I.#P"
# }

# vcs_branch.sh {
	export TMUX_POWERLINE_SEG_VCS_BRANCH_MAX_LEN="24"
	export TMUX_POWERLINE_SEG_VCS_BRANCH_GIT_SYMBOL_COLOUR="202"
	export TMUX_POWERLINE_SEG_VCS_BRANCH_HG_SYMBOL_COLOUR="250"
	export TMUX_POWERLINE_SEG_VCS_BRANCH_SVN_SYMBOL_COLOUR="15"
# }

# vcs_rootpath.sh {
	export TMUX_POWERLINE_SEG_VCS_ROOTPATH_MODE="1"
# }

# mode_indicator.sh {
	export TMUX_POWERLINE_SEG_MODE_INDICATOR_NORMAL_AND_PREFIX_MODE_ENABLED="true"
	export TMUX_POWERLINE_SEG_MODE_INDICATOR_NORMAL_MODE_TEXT="normal"
	export TMUX_POWERLINE_SEG_MODE_INDICATOR_NORMAL_MODE_TEXT_COLOR=""
	export TMUX_POWERLINE_SEG_MODE_INDICATOR_PREFIX_MODE_TEXT="prefix"
	export TMUX_POWERLINE_SEG_MODE_INDICATOR_PREFIX_MODE_TEXT_COLOR=""
	export TMUX_POWERLINE_SEG_MODE_INDICATOR_MOUSE_MODE_ENABLED="true"
	export TMUX_POWERLINE_SEG_MODE_INDICATOR_MOUSE_MODE_TEXT="mouse"
	export TMUX_POWERLINE_SEG_MODE_INDICATOR_MOUSE_MODE_TEXT_COLOR=""
	export TMUX_POWERLINE_SEG_MODE_INDICATOR_COPY_MODE_ENABLED="true"
	export TMUX_POWERLINE_SEG_MODE_INDICATOR_COPY_MODE_TEXT="copy"
	export TMUX_POWERLINE_SEG_MODE_INDICATOR_COPY_MODE_TEXT_COLOR=""
	export TMUX_POWERLINE_SEG_MODE_INDICATOR_SUSPEND_MODE_TEXT="#[bold]suspend#[nobold]"
	export TMUX_POWERLINE_SEG_MODE_INDICATOR_SUSPEND_MODE_TEXT_COLOR=""
	export TMUX_POWERLINE_SEG_MODE_INDICATOR_SEPARATOR_TEXT=" • "
# }
